class Connections():
    def __init__(self):
        self.vertica_connections = {'aws3': {'host': 'internal-qmslb-2120300689.us-west-2.elb.amazonaws.com',
                                             'port': 5433,
                                             'user': 'srvc_pps_quality_admin',
                                             'password': 'ppsquality@123',
                                             'database': 'hp_product_extract',
                                             # autogenerated session label by default,
                                             'session_label': 'some_label',
                                             # default throw error on invalid UTF-8 results
                                             #              'unicode_error': 'strict',
                                             # SSL is disabled by default
                                             'ssl': False,
                                             # using server-side prepared statements is disabled by default
                                             'use_prepared_statements': False,
                                             # connection timeout is not enabled by default
                                             'connection_timeout': 600000,
                                             'unicode_error': 'replace',
                                             'connection_load_balance': True},

                                    'aws_single': {'host': 'internal-qmsdevlb-588520904.us-west-2.elb.amazonaws.com', #admin
                                                   'port': 5433,
                                                   'user': 'srvc_pps_quality_admin',
                                                   'password': 'ppsquality@123',
                                                   'database': 'hp_product_extract',
                                                   # autogenerated session label by default,
                                                   'session_label': 'some_label',
                                                   # default throw error on invalid UTF-8 results
                                                   #              'unicode_error': 'strict',
                                                   # SSL is disabled by default
                                                   'ssl': False,
                                                   # using server-side prepared statements is disabled by default
                                                   'use_prepared_statements': False,
                                                   # connection timeout is not enabled by default
                                                   'connection_timeout': 600000,
                                                   'unicode_error': 'replace',
                                                   'connection_load_balance': True},

                                    'vertica_dev_rd': {'host': 'shr9-vrt-dev-003.inc.hpicorp.net',
                                                       'port': 5433,
                                                       'database': 'shr9_vrt_dev_003',
                                                       'user': 'srvc_qies_dev_read',
                                                       'password': 'QIESquality#123',
                                                       # autogenerated session label by default,
                                                       'session_label': 'some_label',
                                                       # default throw error on invalid UTF-8 results
                                                       #              'unicode_error': 'strict',
                                                       # SSL is disabled by default
                                                       'ssl': False,
                                                       # using server-side prepared statements is disabled by default
                                                       'use_prepared_statements': False,
                                                       # connection timeout is not enabled by default
                                                       'connection_timeout': 600000,
                                                       'unicode_error': 'replace',
                                                       'connection_load_balance': True
                                                       },

                                    'vertica_dev': {'host': 'shr9-vrt-dev-003.inc.hpicorp.net',
                                                    'port': 5433,
                                                    'database': 'shr9_vrt_dev_003',
                                                    'user': 'srvc_pps_quality_admin',
                                                    'password': 'ppsquality@123',
                                                    # autogenerated session label by default,
                                                    'session_label': 'some_label',
                                                    # default throw error on invalid UTF-8 results
                                                    #              'unicode_error': 'strict',
                                                    # SSL is disabled by default
                                                    'ssl': False,
                                                    # using server-side prepared statements is disabled by default
                                                    'use_prepared_statements': False,
                                                    # connection timeout is not enabled by default
                                                    'connection_timeout': 600000,
                                                    'unicode_error': 'replace',
                                                    'connection_load_balance': True
                                                    },

                                    'pro_cdax': {'host': 'shr4-vrt-pro-006.houston.hp.com',
                                                 'port': 5433,
                                                 'database': 'shr4_vrt_pro_006',
                                                 'user': 'srvc_cdax_qms_reader',
                                                 'password': 'PPS%QMS&cdax&123',
                                                 # autogenerated session label by default,
                                                 'session_label': 'some_label',
                                                 # default throw error on invalid UTF-8 results
                                                 #              'unicode_error': 'strict',
                                                 # SSL is disabled by default
                                                 'ssl': False,
                                                 # using server-side prepared statements is disabled by default
                                                 'use_prepared_statements': False,
                                                 # connection timeout is not enabled by default
                                                 'connection_timeout': 600000,
                                                 'unicode_error': 'replace',
                                                 'connection_load_balance': True
                                                 },

                                    'vertica_pro': {'host': 'shr4-vrt-pro-006.houston.hp.com',
                                                    'port': 5433,
                                                    'database': 'shr4_vrt_pro_006',
                                                    'user': 'srvc_pps_qms_read_prd',
                                                    'password': 'pps_qms_prd%2017q2',
                                                    # autogenerated session label by default,
                                                    'session_label': 'some_label',
                                                    # default throw error on invalid UTF-8 results
                                                    #              'unicode_error': 'strict',
                                                    # SSL is disabled by default
                                                    'ssl': False,
                                                    # using server-side prepared statements is disabled by default
                                                    'use_prepared_statements': False,
                                                    # connection timeout is not enabled by default
                                                    'connection_timeout': 600000,
                                                    'unicode_error': 'replace',
                                                    'connection_load_balance': True
                                                    },

                                    'gcsn': {'host': 'shr9-vrt-dev-003.inc.hpicorp.net',
                                             'port': 5433,
                                             'user': 'srvc_pps_css_fdm_dev_read',
                                             'password': 'Forecastcoe1',
                                             'database': 'shr9_vrt_dev_003',
                                             'session_label': 'some_label',
                                             'ssl': False,
                                             'use_prepared_statements': False,
                                             'connection_timeout': 600000,
                                             'unicode_error': 'replace',
                                             'connection_load_balance': True
                                             },


                                    }

        self.sql_connections = {'csdw': {'host': 'vertex.auth.hpicorp.net',
                                         'port': 1433,
                                         'database': 'CSDW',
                                         'username': 'CSDW_Reader',
                                         'password': 'CSDWisdabomb!',
                                         },

                                'sql_cache': {'host': 'gvs12147.austin.hpicorp.net',
                                              'port': 2048,
                                              'database': 'css',
                                              'username': 'srvc_css_qms_reader',
                                              'password': 'nF3k_x84Q__N',
                                              },

                                'sql_cache_surge': {'host': 'gvs12147.austin.hpicorp.net',
                                                    'port': 2048,
                                                    'database': 'css',
                                                    'username': 'srvc_gcsi_GORA_reader',
                                                    'password': 'ice.cream9',
                                                    },

                                'qtools': {'host': 'qtoolssql03.auth.hpicorp.net',
                                           'port': 1433,
                                           'database': 'qtools',
                                           'username': 'qmsread',
                                           'password': 'svcqmsqtr007',
                                           },
                                'qtools_aws': {'host': 'alexandra.corp.hpicloud.net',
                                               'port': 1433,
                                               'database': 'QTOOLS_AWS',
                                               'username': 'cs_translations',
                                               'password': '99ffx57Qcqe1fYFXSkXa',
                                               },
                                'product_info': {'host': 'g1w9755.austin.hpicorp.net',
                                                 'port': 2048,
                                                 'database': 'qcetcomctr',
                                                 'username': 'qcet_read',
                                                 'password': 'Jul@2K21',
                                                 # changed the above password for pmaster database
                                                 },

                                'smart_fleet': {'host': '172.22.254.81',
                                                'port': 1433,
                                                'database': 'Dev_SmartFleet',
                                                'username': 'SmartFleet_Team',
                                                'password': 'A6undanc3!!!',
                                                # not visible in jupyter server
                                                },

                                'a360': {'host': 'g7w10120s.inc.hpicorp.net',
                                        'port': 2048,
                                        'database': 'QCET_EMEA_DEV_DB',
                                        'username':'DataAAT_Read',
                                        'password': 'q3R37$huf*p',
                                       },
                               }
                                    
                                

                                

        self.oracle_connections = {
            'iwms': {'host': 'gvt6407.inc.hpicorp.net',
                     'port': '1525',
                     'database': 'CPIWP',
                     'username': 'srvc_pps_Quality_admin',
                     'password': 'N3W_p4ss_2015'
                     },
            'pwms': {'host': 'gvt6281.inc.hpicorp.net',
                     'port': '1525',
                     'database': 'AMSP',
                     'username': 'srvc_pps_Quality_admin',
                     'password': 'N3W_p4ss_2015'
                     }

        }
